@baseUrl = http://localhost:3000
@orgId = 1016444

### List all orgs with data in the data platform
GET {{baseUrl}}/orgs

### List data sources for an org with details (path param: orgId)
GET {{baseUrl}}/data-sources/{{orgId}}/list

### Preview data for a specific org, product, schema (path params)
GET {{baseUrl}}/data-sources/{{orgId}}/risk_manager/controls_aggregated/preview

### Preview data for a specific org, product, schema (path params)
GET {{baseUrl}}/data-sources/{{orgId}}/risk_manager/controls_aggregated/schema


### Load all data for an org
GET {{baseUrl}}/orgs/{{orgId}}